### ISSUE TITLE
Move to RSpec 3.1

### ISSUE THREAD

**Issue by michaelklishin** [ruby-amqp/amq-protocol#46]

**Comment by dbyron0** [comment]
Does this include removing the warnings that rspec issues with config.warnings set to true?

**Comment by michaelklishin** [comment]
@dbyron0 ideally. I haven't seen them :)

**Comment by dbyron0** [comment]
I saw a bunch but they're gone now.  If I see them again and can convince myself it's not my fault, I'll post 'em.

**Comment by michaelklishin** [comment]
@dbyron0 to clarify: are you working on this issue?

**Comment by dbyron0** [comment]
I wasn't, but then I did.  https://github.com/ruby-amqp/amq-protocol/pull/48 is I think most of it.

**Comment by michaelklishin** [comment]
Now tests fail on anything above 1.8.7.

**Comment by michaelklishin** [comment]
@priviterag if this is done, please close it.

**Comment by priviterag** [comment]
@michaelklishin yep, no more warnings
