### ISSUE TITLE
Support multiple hosts through a connection string

### ISSUE THREAD

**Issue by bradrobertson** [ruby-amqp/amq-protocol#63]
Right now the only way to provide multiple hosts to the bunny gem is through the hash based opts, which is inconvenient from an ENV var perspective. Normally we'd like to set one value for the connection. Unfortunately if I want to use multiple hosts for failover, I can't seem to do this using the gem right now.
The `URI.parse` option appears to fail.

Do you have any thoughts for allowing multiple hosts through a connection URI ? Perhaps just a comma separated list? [MongDB allows us to do this](https://docs.atlas.mongodb.com/driver-connection/#ruby-driver-example) for instance

**Comment by michaelklishin** [comment]
That wouldn't get you anything unless Bunny can somehow use that. I find this feature to be really ugly and `AMQ::URI.parse` currently returns a single hash of connection parameters.

I would consider a new function but don't buy the benefits. You can set environment variables to JSON values if you really have to and parse those to get a list of hashes.

Feel free to look into a PR for both this gem and Bunny but I would only consider a new function in this library.

**Comment by michaelklishin** [comment]
Closed as a question.

**Comment by michaelklishin** [comment]
I'm not sure what specifically you mean by "the `URI.parse` option appears to fail` because it doesn't for me:

```
2.4.1 :003 > URI.parse("amqp://mercurio,urano:5672/%2F")
 => #<URI::Generic amqp://mercurio,urano:5672/%2F>
2.4.1 :004 > u = URI.parse("amqp://mercurio,urano:5672/%2F")
 => #<URI::Generic amqp://mercurio,urano:5672/%2F>
2.4.1 :005 > u.hostname
 => "mercurio,urano"
```

MongoDB's Ruby driver's approach of [supporting multiple URIs in a single string](https://github.com/mongodb/mongo-ruby-driver/blob/93abe0c19cd877c9e132d30fb311c90058a64271/lib/mongo/uri.rb) is… a really fun thing to fix issues in, I suppose.

It might be easier to support `:uris` in Bunny one way or another, then you can parse them out from environment variables however you prefer.

**Comment by michaelklishin** [comment]
The .NET client uses an abstraction called `endpoint` internally. We can convert Bunny to do something similar and then `:hosts`, `:addresses`, `:uris` can be converted to that. In fact, this has been my intent for a while.

**Comment by bradrobertson** [comment]
Ah you're right about `URI.parse`. I must have had a real syntax error in the one I tried. 

Sorry I know this was a question rather than bug, is there a better place to have this discussion?

Basically, the use-case allows us to not have to modify the Bunny constructor interface (connection_string + options), but allow it to support highly available rabbitmq clusters. This is useful because we have 30+ services using rabbitmq and a simple env var update is far preferable to changing our implementation. I'm sure I'm not the only one with this issue.

So it may not be applicable to this gem. I just noticed this is where the connection_string was being parsed.

I'm quite happy to contribute to this so just let me know what you'd like next, or a better place to have this conversation.

**Comment by michaelklishin** [comment]
With `:uris` you'd have to change the services a bit but it can be a line or two: just parse an environment variable value (e.g. by splitting a comma-separated string) and pass a different option to Bunny.

Does that sound realistic?

**Comment by bradrobertson** [comment]
Right now, unless I'm mistaken, the only opts that can have multiple values are hosts (and addresses), but if you're going full-blown `uris` as an option, each one of those uris can now have completely different values for `scheme`, `user` etc.

Ultimately this idea makes sense, but it's a lot more work (since there's an underlying assumption with the current impl that an option like `port` is always the same.  It really just depends how much work you want put into this. Right now I'm getting around this limitation like so
```ruby
connection_opts = AMQ::Settings.parse_amqp_url(ENV['RABBITMQ_URL'])
connection_opts[:hosts] = connection_opts.delete(:host).split(',')
Bunny.new(connection_opts, automatically_recover: true)
```
and that works. So the simplest option is to just change the `parse_amqp_url` to always return `hosts` instead of just `host`, but I don't know *what else* uses that gem/method.

**Comment by michaelklishin** [comment]
amqp gem does. We can introduce a new parsing method that returns `:hosts` and use that in Bunny.

I'm happy to accept more extensive changes to support `:uris` for `2.8.0`, for example.
