### ISSUE TITLE
Timestamp is a 64-bit integer

### ISSUE THREAD

**Issue by carlhoerberg** [ruby-amqp/amq-protocol#64]
Timestamps are encoded as 64bit integers but are here decoded as two 32 bit numbers. Normally this works well when the timestamp is a 32bit number, but not when it has millisecond precision. 

At https://github.com/ruby-amqp/amq-protocol/blob/dd48b32bbb61ec7c7b0f18e751e272c8fdfbd9a2/lib/amq/protocol/table_value_decoder.rb#L135
instead of
```
timestamp = data.slice(offset, 8).unpack(PACK_UINT32_X2).last
```

we should do
```
timestamp = data.slice(offset, 8).unpack("Q>").first
```

And at encoding:

https://github.com/ruby-amqp/amq-protocol/blob/c292d823fb48750531ed2e601ce966ca3a8d4763/lib/amq/pack.rb#L9

```
UINT64 = "Q>".freeze
```

To do big-endian (network-endian) encoding and not platform/native endian.

**Comment by michaelklishin** [comment]
@carlhoerberg thank you. Can you please submit a PR?
