### ISSUE TITLE
String conversion error when encoding message properties and headers

### ISSUE THREAD

**Issue by bbascarevic-tti** [ruby-amqp/amq-protocol#76]
There is a string encoding issue in `table_value_encoder.rb`. Relevant lines:

```
      def self.encode(value)
        accumulator = String.new

        case value
        when String then
          accumulator << TYPE_STRING
          accumulator << [value.bytesize].pack(PACK_UINT32)
          accumulator << value
        when Symbol then
           ...
```

The problem is that the line `accumulator << value` fails if the encoding of `value` is UTF-8 and any of the bytes in `accumulator` is greater than 0x79. The error is "incompatible character encodings: ASCII-8BIT and UTF-8".

`String.new` produces a (binary) string with `ASCII-8BIT` encoding. If the string is empty, inserting any string with any encoding will convert the receiver to the encoding of the inserted string. But if the receiver string is not empty, it will try to convert it to the encoding of the inserted string, and will fail if the receiver contains bytes greater than 0x79, since in all likeliness those are not valid UTF-8 sequences.  Such bytes may exist in the `accumulator` because of the previous line `[value.bytesize].pack(PACK_UINT32)`. 

The proposition is to use ` accumulator << value.force_encoding(accumulator.encoding)` (which is binary `ASCII-8BIT`), as it's already done in table.rb over the entire result of calling `encode`.

**Comment by michaelklishin** [comment]
Please submit a PR.
